openapi: 3.0.0
info:
  version: '1.0'
  title: "User Story #1"
  description: Voglio poter vedere le foto scattate in una determinata location per farmi un’idea del posto
  license:
    name: MIT
servers:
  - url: http://assignments-api.herokuapp.com.com/api/v1
    description: Heroku
  - url: http://localhost:3000/api/v1
    description: Localhost
paths:
  /locations/{id}:
    get:
      description: >-
        Gets information about a specific location, identified by an ID
      summary: Get a location
      parameters:
        - in: path
          name: id
          schema:
            type: String
          required: true
          description: 'ID of the requested location'
      responses:
        '200':
          description: 'The location corresponding to the input ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          description: 'Insert ID doesn't exist'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
  /locations/:
    get:
      description: >-
        Gets information about all existing locations
      summary: Get all locations
      parameters:
      responses:
        '200':
          description: 'All the existing locations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          description: 'There are no existing locations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
    post:
      description: >-
        Creates a new location.
      summary: Create a new location
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - address
                - description
                - image
                - category
              proprieties:
                _id:
                  type: number
                  description: 'ID of the location in database'
                name:
                  type: string
                  description: 'name of the location'
                address:
                  type: string
                  description: 'address of the location'
                description:
                  type: string
                  description: 'description of the location'
                image:
                  type: string
                  description: 'path of the image related to location'
                category:
                  type: string
                  description: 'category of the location'
                likes:
                  type: number
                  description: 'numeber of likes of the post'
      responses:
        '201':
          description: 'Location created. Link in the location header'
          header:
            'Location':
              schema:
                type: string
              description: Link to the created location.
        '500':
          description: 'Error in creating location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          
components:
  schemas:
    Location:
      type: object
      required:
        - id
        - name
        - address
        - description
        - image
        - category
        - likes
      properties:
        id:
          type: String
          description: 'ID of the location'
        name:
          type: String
          description: 'Name of the location'
        address:
          type: String
          description: 'Address of the location'
        description:
          type: String
          description: 'Short description of the location'
        image:
          type: String
          description: 'Representative image of the location'
        category:
          type: String
          description: 'Most Representative category of the location'
        likes:
          type: Number
          description: 'Number of people who likes this element'  
